openapi: 3.1.0
info:
  title: Strinova Champion Queue REST API Specification
  description: Strinova Champion Queue REST API Specification
servers:
  - url: '/api'
components:
  schemas:
    UpdatePlayerRequest:
      type: object
      properties:
        discordId:
          type: string
          example: "839201456789123456"
        uid:
          type: string
          example: "104582"
        playerName:
          type: string
          example: "Test1"
    PlayerRequest:
      type: object
      properties:
        discordId:
          type: string
          example: "839201456789123456"
        uid:
          type: string
          example: "104582"
        playerName:
          type: string
          example: "Test1"
    AccountStatus:
      type: string
      enum:
        - BANNED
        - ACTIVE
    PlayerResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        discordId:
          type: string
          example: "839201456789123456"
        uid:
          type: string
          example: "104582"
        playerName:
          type: string
          example: "Test1"
        elo:
          type: integer
          example: 0
        wins:
          type: integer
          example: 0
        losses:
          type: integer
          example: 0
        accountStatus:
          $ref: '#/components/schemas/AccountStatus'
          example: "ACTIVE"

    PlayersResponse:
      type: object
      properties:
        players:
          type: array
          items:
            $ref: '#/components/schemas/PlayerResponse'
paths:
  /players:
    get:
      summary: Get all players
      tags:
        - Player
      responses:
        '200':
          description: Information of all players.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayersResponse'
    put:
      summary: Update a player information
      tags:
        - Player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePlayerRequest'
      responses:
        '200':
          description: Information of a player.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerResponse'
    post:
      summary: Register new player
      tags:
        - Player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerRequest'
      responses:
        '200':
          description: Information of a new player.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerResponse'
  /players/{discordId}:
    get:
      summary: Get a player
      tags:
        - Player
      parameters:
        - name: discordId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Information of a player.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerResponse'
        '404':
          description: Player not found.
  /players/ban/{discordId}:
    put:
      summary: Ban a player
      tags:
        - Player
      parameters:
        - name: discordId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content.
  /players/unban/{discordId}:
    put:
      summary: Unban a player
      tags:
        - Player
      parameters:
        - name: discordId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content.