openapi: 3.1.0
info:
  title: Strinova Champion Queue REST API Specification
  description: Strinova Champion Queue REST API Specification
servers:
  - url: '/'
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
          example: "test1"
        password:
          type: string
          example: "test123"
        email:
          type: string
          example: "test@example.com"
        discordId:
          type: string
          example: "839201456789123456"
    UserResponse:
      type: object
      properties:
        discordId:
          type: string
          example: "839201456789123456"
        email:
          type: string
          example: "test@example.com"
        username:
          type: string
          example: "test1"
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          example: "test1"
        password:
          type: string
          example: "test123"
    LoginResponse:
      type: object
      properties:
        discordId:
          type: string
          example: "839201456789123456"
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MSIsImp0aSI6IjUzMTlmYTBkLTNhY2YtNGI1YS1iNzE3LWY1OGE2NzljNjIzNiIsImlhdCI6MTc2NzQ3NTQyNCwiZXhwIjoxNzY3NDc5MDI0fQ.zLddayiB3hthtsJcif-ikxMQ0nRikj-Q4fjv7tFxdAI"
        username:
          type: string
          example: "test1"
    UpdatePlayerRequest:
      type: object
      properties:
        uid:
          type: string
          example: "104582"
        playerName:
          type: string
          example: "Test1"
    PlayerRequest:
      type: object
      properties:
        uid:
          type: string
          example: "104582"
        playerName:
          type: string
          example: "Test1"
    AccountStatus:
      type: string
      enum:
        - BANNED
        - ACTIVE
    PlayerResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        uid:
          type: string
          example: "104582"
        playerName:
          type: string
          example: "Test1"
        elo:
          type: integer
          example: 0
        wins:
          type: integer
          example: 0
        losses:
          type: integer
          example: 0
        accountStatus:
          $ref: '#/components/schemas/AccountStatus'
          example: "ACTIVE"
        userResponse:
          $ref: '#/components/schemas/UserResponse'
    PlayersResponse:
      type: object
      properties:
        players:
          type: array
          items:
            $ref: '#/components/schemas/PlayerResponse'
security:
  - apiKey: []


paths:
  /auth/register:
    post:
      summary: Register new user
      tags:
        - Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Information of the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  /auth/login:
    post:
      summary: User login
      tags:
        - Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /auth/logout:
    post:
      summary: User logout
      security:
        - apiKey: []
          bearerAuth: []
      tags:
        - Authorization
      responses:
        '200':
          description: OK
  /api/players:
    get:
      summary: Get all players.
      tags:
        - Player
      responses:
        '200':
          description: Information of all players.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayersResponse'
    put:
      summary: Update a player information
      security:
        - apiKey: [ ]
          bearerAuth: [ ]
      tags:
        - Player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePlayerRequest'
      responses:
        '200':
          description: Information of a player.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerResponse'
    post:
      summary: Register new player
      security:
        - apiKey: [ ]
          bearerAuth: [ ]
      tags:
        - Player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerRequest'
      responses:
        '200':
          description: Information of a new player.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerResponse'
  /api/players/{discordId}:
    get:
      summary: Get a player
      tags:
        - Player
      parameters:
        - name: discordId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Information of a player.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerResponse'
        '404':
          description: Player not found.
  /api/players/ban/{discordId}:
    put:
      summary: Ban a player
      tags:
        - Player
      parameters:
        - name: discordId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content.
  /api/players/unban/{discordId}:
    put:
      summary: Unban a player
      tags:
        - Player
      parameters:
        - name: discordId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content.